export const CHANGE_DATE = 'changeDate'
export const CLICK_INDICATORS = 'clickIndicators'
export const CLICK_PLATFORMS = 'clickPlatforms'
export const SEARCH_PRODUCT = 'searchProduct'
export const SELECT_PRODUCT = 'selectProduct'
export const CHANGE_FETCH_STATUS = 'changeFetchStatus'